
[[rules]]
	description = "AWS Access Key"
	regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
	tags = ["key", "AWS"]

[[rules]]
	description = "AWS cred file info"
	regex = '''(?i)(aws_access_key_id|aws_secret_access_key)(.{0,20})?=.[0-9a-zA-Z\/+]{20,40}'''
	tags = ["AWS"]

[[rules]]
	description = "AWS Secret Key"
	regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
	tags = ["key", "AWS"]

[[rules]]
	description = "Generic secret"
	regex = '''(?i)(psw|pw|pwd|secret|token|key)(.{0,20})?=.[0-9a-zA-Z\/+]{6,40}'''
	tags = ["generic", "secret"]

[[rules]]
	description = "Generic Credential"
	regex = '''(?i)(dbpasswd|dbuser|dbname|dbhost|api_key|apikey|secret|key|api|password|user|guid|hostname|pw|auth)(.{0,20})?['|"]([0-9a-zA-Z-_\/+!{}/=]{4,120})['|"]'''
	tags = ["key", "API", "generic"]
	# ignore leaks with specific identifiers like slack and aws
	[rules.allowlist]
		description = "ignore slack, mailchimp, aws"
		regexes = [
		    '''xox[baprs]-([0-9a-zA-Z]{10,48})''',
		    '''(?i)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]''',
		    '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
		]

[[rules]]
	description = "High Entropy"
	regex = '''[0-9a-zA-Z-_!{}/=]{4,120}'''
  	file = '''(?i)(dump.sql|high-entropy-misc.txt)$'''
	tags = ["entropy"]
    [[rules.Entropies]]
        Min = "4.3"
        Max = "7.0"
    [rules.allowlist]
        description = "ignore ssh key and pems"
        files = ['''(pem|ppk|env)$''']
        paths = ['''(.*)?ssh''']

[[rules]]
	description = "entropy and regex"
	regex = '''(?i)key(.{0,20})?['|"][0-9a-zA-Z]{16,45}['|"]'''
	tags = ["entropy"]
		[[rules.Entropies]]
			Min = "4.5"
			Max = "5.7"
		[[rules.Entropies]]
			Min = "5.5"
			Max = "6.3"
